workflows:
  android-workflow:
    name: Solar Predictor Android Build
    environment:
      vars:
        PACKAGE_NAME: "com.example.solarpredictor"
      java: "17"
    scripts:
      - echo "⭐ Start Android Build"
      - chmod +x gradlew
      - sh gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
